
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - security.nine.ch
  resources:
  - oauthproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.nine.ch
  resources:
  - oauthproxies/finalizers
  verbs:
  - update
- apiGroups:
  - security.nine.ch
  resources:
  - oauthproxies/status
  verbs:
  - get
  - patch
  - update
